name = "PlayingCards"
uuid = "ecfe714a-bcc2-4d11-ad00-25525ff8f984"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
